Topluluk-Rehberi/topluluk-rehberi

README.md

Frontend İstanbul

---

README.md

Istanbul Coders

---

README.md

Add Ruby Türkiye.

---

README.md

Codefiction'i da listeye eklemek istiyorum.

Codefiction eklendi

---

README.md

Added Hackathon Turkiye

---

README.md

* 2Friday Hackathon
* 2Friday, alışılagelmiş hackathonların dışında, iki haftada bir hackathon organize eder. Yarışmacılar dilediği zaman hackathon maratonuna dahil olur. 14 günde bir Cuma akşamı, yarışmacılar youtube kanalımızda projelerini tanıtırlar.

Added "2Friday Hackathon"

---

README.md

GDG Ankara ve WTM Ankara eklendi.

---

README.md

yeni linkler eklendi - frontend istanbul

---

README.md

Devnot Update

---

CONTRIBUTERS.md

Devnot Ekibi

---

README.md

Kodluyoruz eklendi

---

README.md

Deep Learning Türkiye Topluluğu eklendi ve kodluyoruz için anchor link unutulmuş sanırım o da düzenlendi.

Deep Learning Türkiye Topluluğu eklendi

---

README.md

Coders Antalya gurubunu eklemek istiyoruz.

---

README.md

GDG Ankara ve WTM Ankara Slack bilgisi güncellendi.

GDG Ankara Slack eklendi.

---

README.md

gdg eskisehir added

---

README.md

Sakarya Coders topluluğuna ait linkler listeye eklendi.

Sakarya Coders listeye eklendi

---

README.md

GDG Antalya eklendi

---

README.md

SCTurkey için sosyal medya linklerini ekledik.

Adds additional social media links to SCTurkey

---

README.md

Bursa I/O added.
* Topluluk Adı

Bursa I/O eklendi.

---

README.md

Kocaeli Üniversitesi Bilgisayar Kulübü, IEEE Kocaeli Üniversitesi Computer Society, toplulukları eklendi.
* Topluluk Adı

Kocaeli Üniversitesi'nde ki Topluluklar Eklendi

---

README.md

GDG Tekirdağ Added

---

README.md

GDG Cloud Ankara Meetup ve Slack adresleri eklendi.

GDG Cloud Ankara eklendi

---

README.md

ankaraphp eklendi

---

README.md

liste alfabetik sıraya göre düzenlendi

---

README.md

added Bursa I/O

---

CONTRIBUTERS.md
README.md
community-pages/IstanbulFlow/README.md
community-pages/JuniorTalks/README.md
community-pages/KadinBilisimci/README.md
community-pages/RLadiesIstanbul/README.md
community-pages/Recoded/README.md
community-pages/TasarimMutfagi/README.md
community-pages/TurkishWin/README.md

I've added 7 communities. If you accept this branch, must change README.me link by yourself.
Example : | Istanbul DevOps Turkey | [Istanbul DevOps Turkey]https://github.com/mertceyhan/topluluk-rehberi/tree/master/community-pages/istanbulDevOpsTurkey | |
from mertceyhan to yusufcakmak

newcommunitys

---

README.md

I changed links as yusufcakmak

links changed

---

CONTRIBUTERS.md
README.md
community-pages/DortPodcast/README.md

Dort Podcast added.

---

README.md
community-pages/Voİstanbul/README.md

Voistanbul

---

README.md

Adds Codefiction website URL to the main readme file.

Adds Codefiction website URL.

---

CONTRIBUTERS.md
README.md
community-pages/UXminimal/README.md

Listeye UX'minimal topluluğumuzu ve contributorlara da kendimi ekledim.

UX'minimal listeye eklendi

---

community-pages/BAUYazilimveBilisimKulubu/README.md

BAU Yazılım ve Bilişim Kulübü

---

docs/data.yml

AGU Computer Society topluluğunu ekledim.

add agu computer society

---

community-pages/AndroidTurkiye/README.md

Add Android Türkiye group.

---

flutter_app/README.md

Flutter App readme güncellendi.

readme updated

---

docs/data.yml

- Kommunity sayfası oluşturuldu
- Tanıtım sayfası güncellendi

Yazılım ve Bilişim Kulübü - Kommunity

---

docs/data.yml

Topluluk bilgilerinizi [https://github.com/yusufcakmak/topluluk-rehberi/blob/master/docs/data.yml](data.yml) dosyasına eklemeniz gerekmekte.
* Topluluk Adı

Added yazilimtoplulugu.com
